pipeline {
    agent any

    stages {
        stage('Clone'){
            steps{
                git 'https://github.com/arjunthazhath2001/one-data-solutions.git'
            }
        }

        stage('Build Docker Image'){
            steps{
                dir('task1'){
                    script{
                        dockerImage = docker.build("flask-task1-app")
                    }
                }
            }
        }

        stage('Run Docker Container'){
            steps{
                script{
                    dockerImage.run("-p 5000:5000")
                }
            }
        }
    }
}