pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/arjunthazhath2001/one-data-solutions.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('task1') {
                    script {
                        dockerImage = docker.build("flask-task1-app")
                    }
                }
            }
        }

        stage('Clean Old Containers') {
            steps {
                script {
                    sh 'docker ps -q --filter "publish=5000" | xargs -r docker rm -f'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    dockerImage.run("-p 5000:5000")
                }
            }
        }
    }

    post {
        success {
            emailext(
                to: 'arjunta32@gmail.com',
                subject: 'Build Successful',
                body: "Good news! The build was successful.\nCheck it at ${env.BUILD_URL}"
            )
        }
        failure {
            emailext(
                to: 'arjunta32@gmail.com',
                subject: 'Build Failed',
                body: "Unfortunately, the build failed.\nCheck details at ${env.BUILD_URL}"
            )
        }
    }
}
